# Generated by Django 2.0.13 on 2020-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('path', models.FilePathField()),
            ],
        ),
    ]
